[package]
name = "simple-page"
version = "0.1.0"
authors = ["Victor Quiroz Castro <victorhqc@gmail.com>"]
edition = "2018"

[dependencies]
gotham = "0.3.0"
askama = "0.8.0"
hyper = "0.12.32"
hyper-tls = "0.3.2"
mime = "0.3.13"
dotenv = "0.14.1"
url = "1.7.2"
